[openai]
# OpenAI API key used for LLM and DALL·E 3 requests
# 申请地址：https://platform.openai.com/account/api-keys
api_key = "sk-your-key"
# Optional custom base url, leave empty to use the default api.openai.com endpoint
base_url = ""
# Chat/completions model used for workflow reasoning
model = "gpt-4o-mini"
# DALL·E 3 compatible image model identifier
image_model = "gpt-image-1"
# Optional temperature override (0-2). Lower keeps outputs deterministic.
temperature = 0.3

[xunfei_tts]
# Credentials for the Xunfei (iFlytek) Text-to-Speech WebAPI v2 service
# 申请地址：https://www.xfyun.cn/services/online_tts
app_id = ""
api_key = ""
api_secret = ""
voice = "xiaoyan"
format = "mp3"
speed = 50

[dashscope_music]
# 阿里云 DashScope 音乐生成配置
# 申请地址：https://dashscope.aliyun.com/
api_key = ""
model = "text-to-music-001"
style = "中国古风"
duration_seconds = 120

[dashscope_ambience]
# 阿里云 DashScope 环境音效配置（同样使用音频生成能力，可与音乐共用密钥）
# 申请地址：https://dashscope.aliyun.com/
api_key = ""
model = "text-to-music-001"
style = "中国场景环境音"
duration_seconds = 45

[deepseek]
# DeepSeek 大模型调用配置
# 申请地址：https://platform.deepseek.com/
api_key = ""
base_url = ""
model = "deepseek-chat"
temperature = 0.3
timeout_seconds = 60
trust_env = true  # 是否继承系统代理。若需禁用代理可改为 false。
# verify 可写 true/false 或 CA 证书路径；默认继承 httpx 行为
verify = true

[doubao]
# 火山引擎豆包图像生成配置
# 申请地址：https://www.volcengine.com/product/doubao
api_key = ""
base_url = ""
model = "doubao-vision"
negative_prompt = ""
timeout_seconds = 60
trust_env = true
verify = true

[text_generation]
# 可选 provider: "openai"（默认）或 "deepseek"
provider = "openai"

[image_generation]
# 可选 provider: "openai"（默认）或 "doubao"
provider = "openai"

[storage]
# Directory where synthesized media will be stored
output_dir = "./var/output"
